/**
 * marks.js — the pure logic of heading marks (status and star).
 *
 * No `vscode` dependency, so it is unit-tested with plain Node.
 *
 * Marks of notebooks and Markdown files alike are kept in the project's
 * `.vscode/notebook-headings.json` (see MarksFile in src/extension.js), so the
 * documents themselves are never changed. Each file's entry maps a heading's
 * index in the file to its mark, saved with the heading's text:
 *
 *     { "marks": { "code/Analysis.ipynb": { "4": { "status": "todo", "star": true, "text": "Setup" } } } }
 *
 * The text keeps a mark on its heading when headings are added or removed
 * above it; the index keeps it when the heading is renamed (see
 * resolveMarks()).
 *
 * Version 1.5 kept notebook marks in the Jupyter metadata of the heading's
 * cell instead, under MARKS_KEY, keyed by the heading's index within the cell.
 * Those are still read (see combineMarks()) and move to the file the first
 * time a mark in that cell changes.
 */
'use strict';

/** Cell metadata key of the marks saved by version 1.5. */
const MARKS_KEY = 'notebook_headings';

/**
 * Status marks, in picker order.
 * - In the tree, a status replaces the heading's level shape with the icon
 *   media/status/<id>.svg: a filled circle in `fill` with a white glyph
 *   (generated by scripts/status-icons.js; run `npm run icons` after changes).
 *   There is no red: it would blend into the red text of `##` headings.
 * - `icon` is a codicon with the same glyph, for the pickers, where only
 *   codicons can be shown.
 * - `symbol` is a plain text character with that glyph's shape, used in a
 *   parent's summary (a tree item's description can only hold plain text).
 * - `open` statuses (not finished) are listed by Show Marked Headings.
 * Labels are English and translated at runtime through vscode.l10n.
 */
const STATUSES = [
  { id: 'todo', label: 'TODO', fill: '#E8538F', icon: 'circle-large-outline', symbol: '○', open: true },
  { id: 'doing', label: 'In progress', fill: '#12A39B', icon: 'play', symbol: '➤', open: true },
  { id: 'question', label: 'To check', fill: '#6E62E5', icon: 'question', symbol: '?', open: true },
  { id: 'done', label: 'Finished', fill: '#2EA043', icon: 'check', symbol: '✓', open: false },
];

/** Color of the starred-heading icon (white star on a gold circle). */
const STAR_FILL = '#E8A317';

const statusById = (id) => STATUSES.find((s) => s.id === id);

/**
 * A marks object (heading slot -> mark) cleaned up: unknown statuses and
 * malformed entries are dropped. `text` is kept when present.
 *
 * @param {*} raw
 * @returns {Object<string, { status?: string, star?: boolean, text?: string }>}
 */
function cleanMarks(raw) {
  const out = {};
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return out;
  for (const [slot, m] of Object.entries(raw)) {
    if (!/^\d+$/.test(slot) || !m || typeof m !== 'object') continue;
    const mark = {};
    if (statusById(m.status)) mark.status = m.status;
    if (m.star === true) mark.star = true;
    if (!Object.keys(mark).length) continue;
    if (typeof m.text === 'string') mark.text = m.text;
    if (Number.isInteger(m.n) && m.n > 0) mark.n = m.n;
    out[slot] = mark;
  }
  return out;
}

/**
 * The marks stored in a cell's Jupyter metadata, cleaned up.
 *
 * @param {object} jupyterMeta the cell's Jupyter metadata (may be undefined)
 * @returns {Object<string, { status?: string, star?: boolean, text?: string }>} by heading slot
 */
function readMarks(jupyterMeta) {
  return cleanMarks(jupyterMeta && jupyterMeta[MARKS_KEY]);
}

/**
 * Which occurrence of its text each heading is: 0 for the first heading with
 * that text, 1 for the second, and so on.
 *
 * @param {string[]} texts
 * @returns {number[]}
 */
function occurrences(texts) {
  const seen = new Map();
  return texts.map((t) => {
    const n = seen.get(t) || 0;
    seen.set(t, n + 1);
    return n;
  });
}

/**
 * Match stored marks to the headings a container (a notebook or a Markdown
 * file) holds now. A mark is saved with its heading's text and, when several
 * headings share that text, which of them it is (`n`: 0 = the first). It goes
 * to the heading with that text and occurrence, so adding, removing or moving
 * other headings does not move it to a neighbor — not even to another
 * "Summary". If the text is still there but that occurrence is not, it goes
 * to the same-text heading nearest its saved index. A mark whose text is gone
 * (the heading was renamed) or that has no text (saved by version 1.5) falls
 * back to its saved index, if that heading is not already claimed. Marks
 * matching nothing are dropped.
 *
 * @param {Object<string, object>} marks as returned by cleanMarks()/readMarks()
 * @param {string[]} texts the container's heading texts, by index
 * @returns {({ status?: string, star?: boolean } | undefined)[]} by index
 */
function resolveMarks(marks, texts) {
  const out = new Array(texts.length).fill(undefined);
  const occ = occurrences(texts);
  const strip = ({ status, star }) => ({ ...(status ? { status } : {}), ...(star ? { star } : {}) });
  const pending = [];
  for (const [key, mark] of Object.entries(marks || {})) {
    const slot = Number(key);
    if (mark.text === undefined) {
      pending.push([slot, mark]);
      continue;
    }
    const n = mark.n || 0;
    let at = texts.findIndex((t, i) => t === mark.text && occ[i] === n && !out[i]);
    if (at < 0) {
      // That occurrence is gone: the nearest unclaimed heading with the text.
      let best = Infinity;
      texts.forEach((t, i) => {
        if (t === mark.text && !out[i] && Math.abs(i - slot) < best) {
          best = Math.abs(i - slot);
          at = i;
        }
      });
    }
    if (at >= 0) out[at] = strip(mark);
    else pending.push([slot, mark]);
  }
  for (const [slot, mark] of pending) {
    if (slot < texts.length && !out[slot]) out[slot] = strip(mark);
  }
  return out;
}

/**
 * New marks for a container after changing one heading's mark: every mark
 * is resolved against the current headings and saved again under its current
 * slot together with its heading's text (which also upgrades marks saved by
 * older versions). `patch.status` null clears the status, `patch.star` false
 * removes the star; empty marks are left out.
 *
 * @param {Object<string, object>} marks current marks (see cleanMarks())
 * @param {string[]} texts the container's heading texts, by slot
 * @param {number} slot the heading to change
 * @param {{ status?: string|null, star?: boolean }} patch
 * @returns {Object<string, { status?: string, star?: boolean, text: string }>}
 */
function updateMarks(marks, texts, slot, patch) {
  const resolved = resolveMarks(marks, texts);
  const mark = { ...(resolved[slot] || {}) };
  if ('status' in patch) {
    if (patch.status && statusById(patch.status)) mark.status = patch.status;
    else delete mark.status;
  }
  if ('star' in patch) {
    if (patch.star) mark.star = true;
    else delete mark.star;
  }
  resolved[slot] = Object.keys(mark).length ? mark : undefined;
  const occ = occurrences(texts);
  const out = {};
  resolved.forEach((m, i) => {
    if (m) out[i] = { ...m, text: texts[i], ...(occ[i] ? { n: occ[i] } : {}) };
  });
  return out;
}

/**
 * The marks of a notebook's headings: those saved in the marks file, and for
 * headings without one, those still in their cell's metadata (version 1.5).
 *
 * @param {{ text: string, pos: number, cellSlot: number }[]} headings all
 *        headings in document order; `pos` is the cell index and `cellSlot`
 *        the heading's index within its cell
 * @param {Object<string, object>} fileMarks the notebook's entry in the marks
 *        file (see cleanMarks()), keyed by heading index
 * @param {(pos: number) => Object<string, object>} cellMarksAt marks in a
 *        cell's metadata (see readMarks())
 * @returns {{ marks: Object<string, object>, legacy: Set<number> }} `marks`
 *        keyed by heading index, with texts, ready for updateMarks(); `legacy`
 *        the indexes of headings whose mark came from cell metadata
 */
function combineMarks(headings, fileMarks, cellMarksAt) {
  const texts = headings.map((h) => h.text);
  const fromFile = resolveMarks(fileMarks, texts);
  const occ = occurrences(texts);
  const byCell = new Map();
  headings.forEach((h, i) => {
    if (!byCell.has(h.pos)) byCell.set(h.pos, []);
    byCell.get(h.pos)[h.cellSlot] = i;
  });
  const marks = {};
  const legacy = new Set();
  for (const [pos, indexes] of byCell) {
    const stored = cellMarksAt(pos);
    const fromCell = stored && Object.keys(stored).length ? resolveMarks(stored, indexes.map((i) => headings[i].text)) : [];
    indexes.forEach((i, slot) => {
      const mark = fromFile[i] || fromCell[slot];
      if (!mark) return;
      if (!fromFile[i]) legacy.add(i);
      marks[i] = { ...mark, text: headings[i].text, ...(occ[i] ? { n: occ[i] } : {}) };
    });
  }
  return { marks, legacy };
}

/**
 * Whether a heading's text contains one of the in-progress markers (by
 * default "???"), so headings already flagged by hand show as in progress.
 *
 * @param {string} text
 * @param {string[]} markers
 * @returns {boolean}
 */
function hasMarker(text, markers) {
  return (markers || []).some((m) => typeof m === 'string' && m && text.includes(m));
}

/**
 * The heading texts of every container, by slot: `containerOf(node)` names
 * the container (a cell index in notebooks; one shared key for a Markdown
 * file, where `slot` is the heading's index in the file).
 *
 * @param {object[]} flat nodes in document order (with `slot`)
 * @param {(node: object) => *} containerOf
 * @returns {Map<*, string[]>}
 */
function textsByContainer(flat, containerOf) {
  const map = new Map();
  for (const node of flat) {
    const key = containerOf(node);
    if (!map.has(key)) map.set(key, []);
    map.get(key)[node.slot] = node.text;
  }
  return map;
}

/**
 * Set `status`, `autoStatus` and `star` on every node. An explicit status
 * wins over a marker in the text.
 *
 * @param {object[]} flat nodes in document order (with `pos` and `slot`)
 * @param {(key: *) => object} marksOf stored marks of a container, as
 *        returned by cleanMarks()
 * @param {string[]} markers in-progress markers
 * @param {(node: object) => *} [containerOf] a node's container; defaults to
 *        its cell (`pos`)
 */
function assignMarks(flat, marksOf, markers, containerOf = (n) => n.pos) {
  const resolved = new Map();
  for (const [key, texts] of textsByContainer(flat, containerOf)) resolved.set(key, resolveMarks(marksOf(key) || {}, texts));
  for (const node of flat) {
    const mark = resolved.get(containerOf(node))[node.slot] || {};
    node.star = !!mark.star;
    node.autoStatus = !mark.status && hasMarker(node.text, markers);
    node.status = mark.status || (node.autoStatus ? 'doing' : undefined);
  }
}

/** Whether a node carries a mark worth listing (a star or an open status). */
const isMarked = (node) => node.star || (!!node.status && statusById(node.status).open);

/**
 * For every node, count the statuses and stars below it (not its own) in
 * `counts`, e.g. `{ todo: 2, doing: 1, done: 3, star: 2 }`, so a collapsed
 * parent shows what it holds, and collect the statuses found below it in
 * `below` (a Set of ids).
 *
 * @param {object[]} roots
 */
function summarizeMarks(roots) {
  const walk = (node) => {
    const counts = {};
    const below = new Set();
    for (const child of node.children) {
      const sub = walk(child);
      if (child.status) sub[child.status] = (sub[child.status] || 0) + 1;
      if (child.star) sub.star = (sub.star || 0) + 1;
      for (const [k, v] of Object.entries(sub)) counts[k] = (counts[k] || 0) + v;
      if (child.status) below.add(child.status);
      child.below.forEach((s) => below.add(s));
    }
    node.counts = counts;
    node.below = below;
    // Return a copy: the caller adds the child's own status to it.
    return { ...counts };
  };
  roots.forEach(walk);
}

/**
 * File name (in media/status/) of a heading's icon, or undefined when it
 * keeps its level shape:
 * - `group` (a first-level section holding statuses): "group-1101.svg", a
 *   2×2 grid of the statuses in `group` (bits in STATUSES order);
 * - otherwise its own status: "todo.svg";
 * - otherwise "star.svg" when starred.
 * A star on a status or grid icon adds "-star" (a small star over it).
 *
 * @param {{ status?: string, star?: boolean, group?: Iterable<string> }} mark
 * @returns {string|undefined}
 */
function iconFile({ status, star, group }) {
  const set = new Set(group || []);
  const suffix = star ? '-star' : '';
  if (STATUSES.some((s) => set.has(s.id))) {
    return `group-${STATUSES.map((s) => (set.has(s.id) ? '1' : '0')).join('')}${suffix}.svg`;
  }
  if (status && statusById(status)) return `${status}${suffix}.svg`;
  return star ? 'star.svg' : undefined;
}

/** Plain text symbol of starred headings in a summary. */
const STAR_SYMBOL = '★';

/**
 * Summary text for a node's `counts`, e.g. "○2 ➤1 ✓3 ★2": statuses in
 * STATUSES order, then stars; empty when there are none.
 *
 * @param {Object<string, number>} counts
 * @returns {string}
 */
function countsText(counts) {
  if (!counts) return '';
  const parts = STATUSES.filter((s) => counts[s.id]).map((s) => `${s.symbol}${counts[s.id]}`);
  if (counts.star) parts.push(`${STAR_SYMBOL}${counts.star}`);
  return parts.join(' ');
}

/**
 * What "Show Marked Headings" can show: every marked heading (starred or
 * with an open status), only starred ones, or one status.
 */
const MARK_FILTERS = ['marked', 'star', ...STATUSES.map((s) => s.id)];

/** Whether a node passes a mark filter (see MARK_FILTERS). */
function matchesMarkFilter(node, kind = 'marked') {
  if (kind === 'marked') return isMarked(node);
  if (kind === 'star') return !!node.star;
  return node.status === kind;
}

/**
 * Like applyFilter() in headings.js, but keeps the headings that pass a mark
 * filter (see MARK_FILTERS) and their ancestors.
 *
 * @param {object[]} roots
 * @param {string} [kind] 'marked' (default), 'star' or a status id
 * @returns {number} the number of headings that pass
 */
function applyMarkedFilter(roots, kind = 'marked') {
  let count = 0;
  const walk = (node) => {
    node.matchAt = -1;
    const childVisible = node.children.map(walk).some(Boolean);
    const hit = matchesMarkFilter(node, kind);
    if (hit) count++;
    node.visible = hit || childVisible;
    return node.visible;
  };
  roots.forEach(walk);
  return count;
}

module.exports = {
  STATUSES,
  STAR_FILL,
  MARK_FILTERS,
  statusById,
  cleanMarks,
  readMarks,
  resolveMarks,
  updateMarks,
  combineMarks,
  occurrences,
  MARKS_KEY,
  assignMarks,
  summarizeMarks,
  iconFile,
  countsText,
  matchesMarkFilter,
  applyMarkedFilter,
};
