/**
 * marks.js — the pure logic of heading marks (status and star).
 *
 * No `vscode` dependency, so it is unit-tested with plain Node. Marks are
 * stored in the Jupyter metadata of the cell that holds the heading, under
 * MARKS_KEY, keyed by the heading's index within that cell ("0" for the
 * first heading of the cell, "1" for the second, …):
 *
 *     "metadata": { "notebook_headings": { "0": { "status": "todo", "star": true } } }
 *
 * Keying by index rather than by text keeps a mark when the heading is
 * renamed. Jupyter, Jupyter Book and nbconvert ignore this key.
 */
'use strict';

/** Metadata key holding the marks of a cell's headings. */
const MARKS_KEY = 'notebook_headings';

/**
 * Status marks, in picker order.
 * - In the tree, a status replaces the heading's level shape with the icon
 *   media/status/<id>.svg: a filled circle in `fill` with a white glyph
 *   (generated by scripts/status-icons.js; run `npm run icons` after changes).
 *   There is no red: it would blend into the red text of `##` headings.
 * - `icon` is a codicon with the same glyph, for the pickers, where only
 *   codicons can be shown.
 * - `symbol` is a plain text character with that glyph's shape, used in a
 *   parent's summary (a tree item's description can only hold plain text).
 * - `open` statuses (not finished) are listed by Show Marked Headings.
 * Labels are English and translated at runtime through vscode.l10n.
 */
const STATUSES = [
  { id: 'todo', label: 'TODO', fill: '#E8538F', icon: 'circle-large-outline', symbol: '○', open: true },
  { id: 'doing', label: 'In progress', fill: '#12A39B', icon: 'play', symbol: '➤', open: true },
  { id: 'question', label: 'To check', fill: '#6E62E5', icon: 'question', symbol: '?', open: true },
  { id: 'done', label: 'Finished', fill: '#2EA043', icon: 'check', symbol: '✓', open: false },
];

/** Color of the starred-heading icon (white star on a gold circle). */
const STAR_FILL = '#E8A317';

const statusById = (id) => STATUSES.find((s) => s.id === id);

/**
 * The marks stored in a cell's Jupyter metadata, cleaned up: unknown
 * statuses and malformed entries are dropped.
 *
 * @param {object} jupyterMeta the cell's Jupyter metadata (may be undefined)
 * @returns {Object<string, { status?: string, star?: boolean }>} by heading index
 */
function readMarks(jupyterMeta) {
  const raw = jupyterMeta && jupyterMeta[MARKS_KEY];
  const out = {};
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return out;
  for (const [slot, m] of Object.entries(raw)) {
    if (!/^\d+$/.test(slot) || !m || typeof m !== 'object') continue;
    const mark = {};
    if (statusById(m.status)) mark.status = m.status;
    if (m.star === true) mark.star = true;
    if (Object.keys(mark).length) out[slot] = mark;
  }
  return out;
}

/**
 * A copy of a cell's Jupyter metadata with one heading's mark changed.
 * `patch.status` set to null clears the status, `patch.star` false removes
 * the star; empty entries and an empty marks object are removed entirely.
 *
 * @param {object} jupyterMeta
 * @param {number} slot the heading's index within the cell
 * @param {{ status?: string|null, star?: boolean }} patch
 * @returns {object}
 */
function withMark(jupyterMeta, slot, patch) {
  const meta = JSON.parse(JSON.stringify(jupyterMeta || {}));
  const marks = readMarks(meta);
  const mark = { ...(marks[slot] || {}) };
  if ('status' in patch) {
    if (patch.status && statusById(patch.status)) mark.status = patch.status;
    else delete mark.status;
  }
  if ('star' in patch) {
    if (patch.star) mark.star = true;
    else delete mark.star;
  }
  if (Object.keys(mark).length) marks[slot] = mark;
  else delete marks[slot];
  if (Object.keys(marks).length) meta[MARKS_KEY] = marks;
  else delete meta[MARKS_KEY];
  return meta;
}

/**
 * Whether a heading's text contains one of the in-progress markers (by
 * default "???"), so headings already flagged by hand show as in progress.
 *
 * @param {string} text
 * @param {string[]} markers
 * @returns {boolean}
 */
function hasMarker(text, markers) {
  return (markers || []).some((m) => typeof m === 'string' && m && text.includes(m));
}

/**
 * Set `status`, `autoStatus` and `star` on every node. An explicit status
 * wins over a marker in the text.
 *
 * @param {object[]} flat nodes in document order (with `pos` and `slot`)
 * @param {(pos: number) => object} marksAt marks of the cell at `pos`, as
 *        returned by readMarks() (an empty object for Markdown files)
 * @param {string[]} markers in-progress markers
 */
function assignMarks(flat, marksAt, markers) {
  for (const node of flat) {
    const mark = (marksAt(node.pos) || {})[node.slot] || {};
    node.star = !!mark.star;
    node.autoStatus = !mark.status && hasMarker(node.text, markers);
    node.status = mark.status || (node.autoStatus ? 'doing' : undefined);
  }
}

/** Whether a node carries a mark worth listing (a star or an open status). */
const isMarked = (node) => node.star || (!!node.status && statusById(node.status).open);

/**
 * For every node, count the statuses and stars below it (not its own) in
 * `counts`, e.g. `{ todo: 2, doing: 1, done: 3, star: 2 }`, so a collapsed
 * parent shows what it holds, and collect the statuses found below it in
 * `below` (a Set of ids).
 *
 * @param {object[]} roots
 */
function summarizeMarks(roots) {
  const walk = (node) => {
    const counts = {};
    const below = new Set();
    for (const child of node.children) {
      const sub = walk(child);
      if (child.status) sub[child.status] = (sub[child.status] || 0) + 1;
      if (child.star) sub.star = (sub.star || 0) + 1;
      for (const [k, v] of Object.entries(sub)) counts[k] = (counts[k] || 0) + v;
      if (child.status) below.add(child.status);
      child.below.forEach((s) => below.add(s));
    }
    node.counts = counts;
    node.below = below;
    // Return a copy: the caller adds the child's own status to it.
    return { ...counts };
  };
  roots.forEach(walk);
}

/**
 * File name (in media/status/) of a heading's icon, or undefined when it
 * keeps its level shape:
 * - `group` (a first-level section holding statuses): "group-1101.svg", a
 *   2×2 grid of the statuses in `group` (bits in STATUSES order);
 * - otherwise its own status: "todo.svg";
 * - otherwise "star.svg" when starred.
 * A star on a status or grid icon adds "-star" (a small star over it).
 *
 * @param {{ status?: string, star?: boolean, group?: Iterable<string> }} mark
 * @returns {string|undefined}
 */
function iconFile({ status, star, group }) {
  const set = new Set(group || []);
  const suffix = star ? '-star' : '';
  if (STATUSES.some((s) => set.has(s.id))) {
    return `group-${STATUSES.map((s) => (set.has(s.id) ? '1' : '0')).join('')}${suffix}.svg`;
  }
  if (status && statusById(status)) return `${status}${suffix}.svg`;
  return star ? 'star.svg' : undefined;
}

/** Plain text symbol of starred headings in a summary. */
const STAR_SYMBOL = '★';

/**
 * Summary text for a node's `counts`, e.g. "○2 ➤1 ✓3 ★2": statuses in
 * STATUSES order, then stars; empty when there are none.
 *
 * @param {Object<string, number>} counts
 * @returns {string}
 */
function countsText(counts) {
  if (!counts) return '';
  const parts = STATUSES.filter((s) => counts[s.id]).map((s) => `${s.symbol}${counts[s.id]}`);
  if (counts.star) parts.push(`${STAR_SYMBOL}${counts.star}`);
  return parts.join(' ');
}

/**
 * Like applyFilter() in headings.js, but keeps marked headings (starred or
 * with an open status) and their ancestors.
 *
 * @param {object[]} roots
 * @returns {number} the number of marked headings
 */
function applyMarkedFilter(roots) {
  let count = 0;
  const walk = (node) => {
    node.matchAt = -1;
    const childVisible = node.children.map(walk).some(Boolean);
    if (isMarked(node)) count++;
    node.visible = isMarked(node) || childVisible;
    return node.visible;
  };
  roots.forEach(walk);
  return count;
}

module.exports = {
  STATUSES,
  STAR_FILL,
  statusById,
  readMarks,
  withMark,
  assignMarks,
  summarizeMarks,
  iconFile,
  countsText,
  applyMarkedFilter,
};
